before_install:
  - cp vitaes-webapp/src/config-SAMPLE.js vitaes-webapp/src/config.js
  - docker build -t vitaes/webapp ./vitaes-webapp

services:
  - docker

script:
  - docker run vitaes/webapp ./node_modules/.bin/eslint src --ext .jsx --ext .js
