before_install:
  - cp webapp/src/config-SAMPLE.js webapp/src/config.js
  - docker build -t dev-webapp -f ./webapp/Dockerfile.dev ./webapp

services:
  - docker

script:
  - docker run dev-webapp ./node_modules/.bin/eslint src --ext .jsx --ext .js
