version: '3'
services:
  webapp:
    volumes:
    - ./vitaes-webapp/src:/project/src
    - ./vitaes-webapp/public:/project/public
    build: vitaes-webapp/.
    image: vitaes/webapp
    command: yarn start
    networks:
    - net
  server:
    build: vitaes-renderer/.
    image: vitaes/server
    ports:
    - "5000:5000"
    networks:
    - net
  renderer:
    build: vitaes-renderer/.
    command: python3 Consumer.py
    image: vitaes/renderer
    depends_on:
    - rabbitmq
    networks:
    - net
  nginx:
    build: vitaes-nginx/.
    ports:
    - "443:443"
    image: vitaes/nginx
    networks:
    - net
  nginx-http:
    build: vitaes-nginx-http/.
    ports:
    - "80:80"
    image: vitaes/nginxhttp
    networks:
    - net
  rabbitmq:
    image: rabbitmq:alpine
    networks:
    - net
  redis:
    image: redis
    networks:
    - net
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-volume:/var/lib/grafana
    networks:
    - net
  tsdb:
    image: influxdb
    container_name: tsdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - influxdb-volume:/var/lib/influxdb
    networks:
    - net
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: vitaes
    volumes:
    - mongodb:/data/db
    - ./mongobackup:/mbckp
    networks:
    - net
  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - 8081:8081
    depends_on:
    - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: vitaes
    networks:
    - net
volumes:
  mongodb:
    external: true
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
networks:
  net:
