version: 2.1

jobs:

  build:
  
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
  
    docker:
      # specify the version
      - image: circleci/golang:1.9

    steps:
      - checkout:
          path: ~/api
      - setup_remote_docker
      - run:
          name: Setting up docker (Login GCR)
          command: cat ${GCLOUD_SERVICE_KEY} | docker login -u _json_key --password-stdin https://us.gcr.io/vitaes/
      - run: 
          name: Installing API module depedencies
          command: cd api && go mod download
      - run: 
          name: Running API module tests
          command: cd api && go test -v ./...
      - run: 
          name: Compiling API module
          command: cd api && go build
      - run:
          name: Building API module docker image
          command: docker image build -t us.gcr.io/vitaes/api:$CIRCLE_BRANCH .
      - run:
          name: Pushing docker image to gcr
          command: docker image push us.gcr.io/vitaes/api:$CIRCLE_BRANCH
  
  static_analysis:

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/api
    
    docker:
      - image: fabiocorreia/sonarscanner:3.3.0-alpine

    steps:
      - checkout:
          path: ~/api
      - setup_remote_docker
      - run:
          name: running analysis
          command: |
            export SONAR_SCANNER_OPTS="-Xmx2048m"
            sonar-scanner -Dsonar.projectKey=vitaes \
            -Dsonar.sources=. \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.exclusions= \
            -Dsonar.host.url=https://sonarqube.vitaes.tk \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.login=${SONARQUBE_TOKEN}

workflows:
  version: 2
  build_test_and_deliver:
    jobs: 
      - static_analysis