version: 2.1

jobs:

  build:

    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/api
    
    docker:
      - image: fabiocorreia/sonarscanner:3.3.0-alpine

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: running analysis
          command: |
            export SONAR_SCANNER_OPTS="-Xmx2048m"
            sonar-scanner -Dsonar.projectKey=vitaes_api \
            -Dsonar.sources=. \
            -Dsonar.sourceEncoding=UTF-8 \
            -Dsonar.exclusions= \
            -Dsonar.host.url=https://sonarqube.vitaes.tk \
            -Dsonar.projectVersion=1.0 \
            -Dsonar.login=${SONARQUBE_TOKEN}"
      

workflows:
  version: 2
  build_test_and_deliver:
    jobs: 
      - build