apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: k8s.vitaes.io
    http:
      paths:
      - backend:
          serviceName: webapp
          servicePort: 80
  - host: api.k8s.vitaes.io
    http:
      paths:
      - backend:
          serviceName: api
          servicePort: 6000
  - host: storage.k8s.vitaes.io
    http:
      paths:
      - backend:
          serviceName: storage
          servicePort: 6000
  - host: logger.k8s.vitaes.io
    http:
      paths:
      - backend:
          serviceName: logger
          servicePort: 6000
  - host: sqlite.k8s.vitaes.io
    http:
      paths:
      - backend:
          serviceName: sqlite-web
          servicePort: 8080
  - host: grafana.k8s.vitaes.io
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000
