apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: renderer-autoscaler
rules:
  - apiGroups: ["*"]
    resources: ["deployments"]
    verbs: ["get", "list", "update"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: renderer-autoscaler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: renderer-autoscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: renderer-autoscaler
subjects:
- kind: ServiceAccount
  name: renderer-autoscaler
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: renderer-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: renderer-autoscaler
    spec:
      serviceAccountName: renderer-autoscaler
      containers:
      - name: renderer-autoscaler
        image: onfido/k8s-rabbit-pod-autoscaler
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        env:
          - name: INTERVAL
            value: "5"
          - name: RABBIT_HOST
            value: "rabbitmq.default.svc.cluster.local"
          - name: RABBIT_USER
            value: guest
          - name: RABBIT_PASS
            value: guest
          - name: AUTOSCALING
            value: >
              1|10|1|default|renderer|cv_requests
          - name: LOGS
            value: HIGH
