name: backup

on:
  schedule:
  - cron:  '*/15 * * * *'

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install goutte
    - run: goutte goutte.toml ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
